CREATE DATABASE CRUD;
USE CRUD;

CREATE TABLE TASK(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MESSAGE VARCHAR(500) NOT NULL,
    PRIORITY VARCHAR(500) NOT NULL,
    STATE VARCHAR(500) NOT NULL
);